"""empty message

Revision ID: 0d1c2a3f6567
Revises: 478f0bc0ecf7
Create Date: 2022-04-04 12:12:55.821793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1c2a3f6567'
down_revision = '478f0bc0ecf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('deleted_by_recipient', sa.Boolean(), nullable=True))
    op.add_column('message', sa.Column('deleted_by_author', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'deleted_by_author')
    op.drop_column('message', 'deleted_by_recipient')
    # ### end Alembic commands ###
