"""empty message

Revision ID: 4e84345cb546
Revises: 478f0bc0ecf7
Create Date: 2022-04-04 11:57:04.772470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e84345cb546'
down_revision = '478f0bc0ecf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'deleted')
    # ### end Alembic commands ###
