"""subject message

Revision ID: 7999f423e027
Revises: 636c49907e3d
Create Date: 2022-03-15 15:27:36.432313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7999f423e027'
down_revision = '636c49907e3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('subject', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'subject')
    # ### end Alembic commands ###
