"""empty message

Revision ID: a89cd40edfb0
Revises: 0d1c2a3f6567
Create Date: 2022-04-05 10:30:23.403479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a89cd40edfb0'
down_revision = '0d1c2a3f6567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('size', sa.Integer(), nullable=True))
    op.add_column('file', sa.Column('mimetype', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'mimetype')
    op.drop_column('file', 'size')
    # ### end Alembic commands ###
